### PR TITLE
Adds ModelStateDictionary parameter

### PR DESCRIPTION
**Pull request by sasmithjr**
Adds a parameter to renderView for ModelStateDictionary
From issue #8 

Let me know if you'd like anything modified/updated!

### CODE REVIEW

**Comment by sasmithjr** [comment]
Should I have created the PR against the develop branch? I see that it has fixed/changed a couple of issues that seem to be preventing the CI checks from finishing here.

**Comment by dustinmoris** [comment]
Yes, but that's fine I've changed the PR against develop now.

**Comment by dustinmoris** [comment]
The change is pretty minor which is fine with me, I'm just curious how you would use this now?

**Comment by sasmithjr** [comment]
I wasn't sure if it was a good idea to go changing the existing `razorView` and `razorHtmlView` handlers since that'd break any existing users of the handlers, so I'll just go make my own handler specifically to use this. Do you think it makes sense to update the handlers now, as well?

**Comment by sasmithjr** [comment]
@dustinmoris Roger that. I see you're already prepping for a version 3, so I'll make the changes to the handlers, update samples, and update the release notes accordingly tomorrow.

**Pull request merged**
